sudo: required

services:
  - docker

before_install:
  - docker build -t sameer/fib_client -f ./client/Dockerfile.dev ./client

script:
  - docker run sameer/fib_client npm run test -- --coverage

after_success:
  - docker build -t sameer/fib_client ./client
  - docker build -t sameer/fib_api ./server
  - docker build -t sameer/fib_worker ./worker
  - docker build -t sameer/fib_router ./nginx

  # Login to docker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  # Take image and push to docker hub
  - docker push sameer/fib_client
  - docker push sameer/fib_api
  - docker push sameer/fib_worker
  - docker push sameer/fib_router
